package common

object CLErrors {
    const val NETWORK_CONNECTION_ERROR = "Network connection error"
    const val CANT_BE_BLANK = "can't be blank"
    const val EMAIL_NOT_FOUND_ERROR = "Email not found"
    const val INVALID_USER_ERROR = "Invalid User"
    const val LOGIN_ERROR = "Invalid Login or password"
    const val MAIL_ALREADY_TAKEN = "email\":[\"has already been taken\"]"
    const val NETWORK_ERROR = "Error: No Network"
    const val OTP_VERIFICATION_FILED = "Account is already verified. Please Login from the App"
    const val PHONE_ALREADY_TAKEN = "phone_number\":[\"has already been taken\"]"
    const val RESET_PASSWORD_TOKEN_INVALID = "reset_password_token: [is invalid]"
    const val REQUEST_ALREADY_SENT = "Request Already sent"
    const val REQUEST_SENT = "Follow request sent successfully"
    const val REQUEST_TIMEOUT = "Request timeout"
    const val SOMETHING_WENT_WRONG = "Something went wrong!"
    const val SESSION_EXPIRED_ERROR = "Not Authenticated/Token Expired"
    const val SESSION_EXPIRED = "Session expired!"
    const val UPDATE_ERROR = "Update Profile Data Failed"
}